name: Checks

on:
  push:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "maven"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean compile package -DskipTests

      - name: Test
        run: mvn test

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Setup Featurevisor example-1 project
        run: |
          mkdir example-1
          (cd example-1 && npx @featurevisor/cli@2.x init --example=1)
          (cd example-1 && npm install)
          (cd example-1 && npx featurevisor test)

      - name: Run Featurevisor project tests against Java SDK
        run: mvn exec:java -Dexec.mainClass="com.featurevisor.cli.CLI" -Dexec.args="test --projectDirectoryPath=example-1"
